### ISSUE TITLE
Grouped error messages

### ISSUE THREAD

**Issue by mattdharmon** [i-am-tom/schemer#4]
I would love to see errors (from an API standpoint) where I would have a field with an array of errors for that field.

```
[
    'username' => [
        'Is blank',
        'Needs at least 6 characters'
    ]
]
```

**Comment by i-am-tom** [comment]
Hey! This is a cool idea - I'll have to put a bit more thought into `Result::concat`, and do something with merging trees of errors, but I love this! I'll get to it today :)

**Comment by i-am-tom** [comment]
So, I've given this some thought: I wouldn't want to add deep merging to Result, as it would mean that Result could output a variety of shapes (an array of strings, or an array of arrays of strings, or an array of arrays...).

In which case, I'll probably implement this as something specific to the `Assoc` and `Collection` validators that will return a (respectively) sequential or associative array of errors, and that can nest as needed. It should also accomplish what's needed in this use case without introducing any BC breaks :)

**Comment by mattdharmon** [comment]
That sounds reasonable to me. It's nice to have choices.

**Comment by i-am-tom** [comment]
So, to keep you updated, this is where I've been going with the idea: https://github.com/i-am-tom/schemer/tree/nested-validation

I've not yet updated the README, but the simple overview is that, for `Assoc` and `Collection`, one can now call `->nestedValidate()`, which will return a `NestedResult`. This object has two properties, `$outer` (for errors on the Assoc/Collection itself), and `$inner` (an array for the inner values' `Result` objects). For doubly-nested structures, `$inner` will also contain `NestedResult` objects, so that deep nesting stays the same.

This is the cleanest way that I can think to do it, but it still looks a bit messy. I'm going to spend some time clearing it up and working out how best to document it, but I think it's getting there :)

**Comment by i-am-tom** [comment]
It's in `master` and can work pretty much exactly as requested :)
